name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 18
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Node
        # uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          node-version: 18
          cache: pnpm
      # - uses: bahmutov/npm-install@v1
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm compile
      - run: pnpm test

      - name: Upload coverage report on Node 18 to coveralls.io...
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
