name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test on Node 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3

      - name: Install Cypress
        run: npx cypress install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: pnpm

      - run: npm install
      - run: npm run check:ts
      - run: npm run lint:ts
      - run: npm run lint:css
      - run: npm run build-vite
      - run: pnp run compile-scss
      - run: npm run clean-coverage
      - run: npx cypress run

      - name: Upload coverage report on Node 20 to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}